name: flake8

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          ignore: "E501,E121,E123,E126,E226,E24,E704,W503,W504"
          exclude: "__init__.py, input/__init__.py"
          path: "pyerrors"
