name: pytest

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "pypy3"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install numpy>=1.16
          pip install scipy
          pip install autograd>=1.2
          pip install numdifftools
          pip install matplotlib
          pip install iminuit<2
          pip install .
          pip install pytest
          pip install pytest-cov
          pip install pytest-benchmark

      - name: Run tests
        run: pytest --cov=pyerrors -v
